name: "olist_dbt_snowflake"

version: "1.0.0"
config-version: 2

profile: "olist_analytics_snowflake"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
models:
  olist_dbt_snowflake:
    intermediate:
      +materialized: view
      +schema: olist_intermediate
    staging:
      +materialized: view
      +schema: olist_staging
    marts:
      +materialized: table
      +schema: olist_marts
      dims:
        +schema: olist_dims
      facts:
        +schema: olist_facts
      executive:
        +schema: olist_marts_executive
      operations:
        +schema: olist_marts_operations
      commercial:
        +schema: olist_marts_commercial
      cx:
        +schema: olist_marts_cx
